// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package org

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrgApiClient is the client API for OrgApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrgApiClient interface {
	GetOrg(ctx context.Context, in *GetOrgRequest, opts ...grpc.CallOption) (*Org, error)
}

type orgApiClient struct {
	cc grpc.ClientConnInterface
}

func NewOrgApiClient(cc grpc.ClientConnInterface) OrgApiClient {
	return &orgApiClient{cc}
}

func (c *orgApiClient) GetOrg(ctx context.Context, in *GetOrgRequest, opts ...grpc.CallOption) (*Org, error) {
	out := new(Org)
	err := c.cc.Invoke(ctx, "/blueapi.org.v1.OrgApi/GetOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrgApiServer is the server API for OrgApi service.
// All implementations must embed UnimplementedOrgApiServer
// for forward compatibility
type OrgApiServer interface {
	GetOrg(context.Context, *GetOrgRequest) (*Org, error)
	mustEmbedUnimplementedOrgApiServer()
}

// UnimplementedOrgApiServer must be embedded to have forward compatible implementations.
type UnimplementedOrgApiServer struct {
}

func (UnimplementedOrgApiServer) GetOrg(context.Context, *GetOrgRequest) (*Org, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrg not implemented")
}
func (UnimplementedOrgApiServer) mustEmbedUnimplementedOrgApiServer() {}

// UnsafeOrgApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrgApiServer will
// result in compilation errors.
type UnsafeOrgApiServer interface {
	mustEmbedUnimplementedOrgApiServer()
}

func RegisterOrgApiServer(s grpc.ServiceRegistrar, srv OrgApiServer) {
	s.RegisterService(&OrgApi_ServiceDesc, srv)
}

func _OrgApi_GetOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgApiServer).GetOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blueapi.org.v1.OrgApi/GetOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgApiServer).GetOrg(ctx, req.(*GetOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrgApi_ServiceDesc is the grpc.ServiceDesc for OrgApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrgApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blueapi.org.v1.OrgApi",
	HandlerType: (*OrgApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrg",
			Handler:    _OrgApi_GetOrg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "org/v1/org.proto",
}
