// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/cover/attribute.proto

package cover

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Display       string                 `protobuf:"bytes,1,opt,name=display,proto3" json:"display,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_api_cover_attribute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_api_cover_attribute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_api_cover_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *Category) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_cover_attribute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_cover_attribute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_cover_attribute_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_cover_attribute_proto protoreflect.FileDescriptor

const file_api_cover_attribute_proto_rawDesc = "" +
	"\n" +
	"\x19api/cover/attribute.proto\x12\x11blueapi.api.cover\":\n" +
	"\bCategory\x12\x18\n" +
	"\adisplay\x18\x01 \x01(\tR\adisplay\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\",\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameBg\n" +
	"\x1fcloud.alphaus.blueapi.api.coverB\x16ApiCoverAttributeProtoZ,github.com/alphauslabs/blue-sdk-go/api/coverb\x06proto3"

var (
	file_api_cover_attribute_proto_rawDescOnce sync.Once
	file_api_cover_attribute_proto_rawDescData []byte
)

func file_api_cover_attribute_proto_rawDescGZIP() []byte {
	file_api_cover_attribute_proto_rawDescOnce.Do(func() {
		file_api_cover_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cover_attribute_proto_rawDesc), len(file_api_cover_attribute_proto_rawDesc)))
	})
	return file_api_cover_attribute_proto_rawDescData
}

var file_api_cover_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_cover_attribute_proto_goTypes = []any{
	(*Category)(nil), // 0: blueapi.api.cover.Category
	(*Result)(nil),   // 1: blueapi.api.cover.Result
}
var file_api_cover_attribute_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_cover_attribute_proto_init() }
func file_api_cover_attribute_proto_init() {
	if File_api_cover_attribute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cover_attribute_proto_rawDesc), len(file_api_cover_attribute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_cover_attribute_proto_goTypes,
		DependencyIndexes: file_api_cover_attribute_proto_depIdxs,
		MessageInfos:      file_api_cover_attribute_proto_msgTypes,
	}.Build()
	File_api_cover_attribute_proto = out.File
	file_api_cover_attribute_proto_goTypes = nil
	file_api_cover_attribute_proto_depIdxs = nil
}
